name: flutter_core
description: A new Flutter package project.
version: 0.0.2
publish_to: none

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  intl: ^0.16.1
  flutter_platform_widgets:
    git:
      url: git://github.com/stryder-dev/flutter_platform_widgets.git
      ref: beta

flutter:
