name: flutter_web
description: Package to provide the default way to perform web requests in our flutter apps.
version: 0.0.2
author:
homepage:

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  connectivity: ^3.0.2
  dio_cookie_manager: ^2.0.0-beta1
  path_provider: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
